<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit980b408b21156853fab367b877e19a85
{
    public static $files = array (
        'd05ecc14ff93fd612a81ec7e8ab4c2c9' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v5p4.php',
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit980b408b21156853fab367b877e19a85::$classMap;

        }, null, ClassLoader::class);
    }
}
